// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pasxkyirxphvkqmgecgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhc3hreWlyeHBodmtxbWdlY2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTQwOTgsImV4cCI6MjA2NTkzMDA5OH0.WVGstIkJoUNmD0xYIVP20VoVDiU4ln4MDQlRjP0GaT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);